[project]
name = "mini-aios"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.52.0",
    "apscheduler>=3.11.2",
    "cryptography>=44.0.0",
    "fastapi>=0.135.1",
    "openai>=2.26.0",
    "python-dotenv>=1.2.2",
    "uvicorn>=0.42.0",
    "zeroconf>=0.148.0",
    "httpx>=0.27.0",
    "ollama",
    "websockets>=12.0",
    "python-multipart>=0.0.22",
    "adafruit-blinka>=9.0.4",
    "adafruit-circuitpython-neopixel-spi>=1.0.15",
    "jetson-gpio>=2.1.12",
    "openai-agents>=0.21.0",
]
